version: '3.9'

services:
  db:
    image: postgres:14-alpine
    ports:
      - ":5432"

    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=dio

    volumes:
      - ./data/db:/var/lib/postgresql/data
  
  web:
    build: 
      context: ./web
      dockerfile: Dockerfile

    ports:
      - "3000:3000"

    volumes:
      - ./web:/app/web  
    
    depends_on:
      - api

  api:
    build:
      context: ./api
      dockerfile: Dockerfile

    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=dio

    ports:
      - '8000:8000'

    volumes:
      - ./api:/app/api

    depends_on:
      - db